### ISSUE TITLE
Is there a reason for this pop?

### ISSUE THREAD

**Issue by sprajjwal** [AcidicNic/TweetGen#1]
I noticed this pop in your setup method that looked like it shouldn't be there. Was there a specific reason you added it?
https://github.com/AcidicNic/CS-12-Intro-To-Data-Structures/blob/fd8096ed3c6022876d7e4b2eee4b701232844bcd/dictionary_words.py#L12

**Comment by AcidicNic** [comment]
https://i.imgur.com/g5NmHMa.png
